# Generated by Django 3.2.13 on 2022-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=700)),
                ('lastname', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='EXPERT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=700)),
                ('lastname', models.CharField(max_length=700000, null=True)),
            ],
        ),
    ]
